spring:
  application:
    name: auth-service
server:
  port: 8082

jwt:
  secret: Thang

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
