version: "3.8"
services:
  name-service:
    container_name: name-service
    build:
      context: ./name-service
      dockerfile: dev.Dockerfile
    volumes:
      - ./name-service/:/app
      - ./.m2/:/root/.m2
    ports:
      - "8761:8761"
      - "35729:35729"
      - "8000:8000"
    working_dir: /app
    command: sh run.sh
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
      - "35749:35749"
      - "8002:8002"
    volumes:
      - ./gateway-service/:/app
      - ./.m2/:/root/.m2
    working_dir: /app
    environment:
      EUREKA_URL: http://name-service:8761/eureka
    command: sh run.sh
    depends_on:
      name-service:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 1m30s
      timeout: 5s
      retries: 3

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: dev.Dockerfile
    ports:
      - "8081:8081"
      - "35739:35739"
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
    volumes:
      - ./user-service/:/app
      - ./.m2/:/root/.m2
    working_dir: /app
    environment:
      EUREKA_URL: http://name-service:8761/eureka/
    command: sh run.sh
    depends_on:
      name-service:
        condition: service_healthy

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: dev.Dockerfile
    ports:
      - "8082:8082"
      - "35759:35759"
      - "8003:8003"
    volumes:
      - ./auth-service/:/app
      - ./.m2/:/root/.m2
    working_dir: /app
    environment:
      EUREKA_URL: http://name-service:8761/eureka
    command: sh run.sh
    depends_on:
      name-service:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 1m30s
      timeout: 5s
      retries: 3