spring:
  application:
    name: gateway-service
  devtools:
    livereload:
      port: 35749
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: ./
server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
