spring:
  application:
    name: user-service
  devtools:
    livereload:
      port: 35739
      enabled: true
server:
  port: ${port:8081}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://name-service:8761/eureka}
